apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-http-server-web
spec:
  template:
    spec:
      containers:
      - name: web
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
